services:
    jmz.hidebots.listener:
        class: jmz\hidebots\event\listener
        arguments:
            - '@config'
            - '@user'            
        tags:
            - { name: event.listener }
